[build]
  command = "npm run build"
  publish = "client/dist"
  base = "client"
  # The base directory should be the path to the nested Vue project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
