[build]
  base = "client"  # Ensure Netlify builds from the client directory
  command = "npm run build-only"  # Skip type-check, only run vite build
  publish = "dist"  # Output directory for the Vite build

[build.environment]
  NODE_VERSION = 20.0.0

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200